# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8fdfd7e8f0f50e7f45a6def79740d4384f5f52d347ec1aacd55bcbd16c1e9f9b7748aa972249b5d79c7c85ca4e6c4580cedb69fede7b517dde5d407a1ef16426

test:
  secret_key_base: 6a00c75245f7a6f7f65672337bf5b4454202293f7693860843ee0a8bc185d2968a28c8dba47d90953d1628d2fa3ca4ff791e7e7d39df3a97f680ac03f5d75679

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
